spring.application.name=taskmaster
management.endpoints.web.exposure.include=health
spring.datasource.url=jdbc:h2:mem:taskmaster
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
