apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: cfr785so0pa80f
    url: https://amrit-ch.website/prometheus/
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST
      tlsSkipVerify: true

  - name: CloudWatch
    type: cloudwatch
    uid: dfr785s213gn4d
    access: proxy
    isDefault: false
    jsonData:
      authType: default
      defaultRegion: ap-south-1
